ARG PACKAGE_NAME="sentrim_1.0_linux_amd64.deb"

FROM ubuntu:latest
ARG PACKAGE_NAME
WORKDIR /tmp
RUN apt-get update
RUN apt-get install -y dpkg-dev
COPY $PACKAGE_NAME /tmp/
COPY cicd/minikube/sentrim-service.sh /tmp/
RUN dpkg -i /tmp/$PACKAGE_NAME
RUN apt-get -f install -y
RUN chmod +x /usr/bin/sentrim

CMD ["/tmp/sentrim-service.sh"]
