name: CI-Pipeline

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: TEST GITHUB ACTIONS
        run: ls -la

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ make

      - name: TEST GITHUB ACTIONS 2
        run: |
          g++ --version
          make --version

      - name: Build program
        run: make
        working-directory: ./src

      - name: TEST GITHUB ACTIONS 3
        run: |
          echo "Trying to run this stuff"
          ./sentrim "l ll lll. llll l ll lll l. ll."
        working-directory: ./usr/bin
