name: CI-Pipeline

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ make

      - name: Build program
        run: |
          mkdir -p ../usr/bin
          make
        working-directory: ./src

      - name: Upload binary to artifact
        uses: actions/upload-artifact@v4
        with:
          name: sentrim-binary
          path: ./usr/bin/sentrim
          retention-days: 1

  Test:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ make tree

      - name: Create usr/bin/ directory
        run: |
          cd ./src
          mkdir -p ./usr/bin
          tree

      - name: Download binary from artifact
        uses: actions/download-artifact@v4
        with:
          name: sentrim-binary
          path: ./usr/bin

      - name: List file system again
        run: ls -la

      - name: Test download success
        run: ./sentrim "test. test testt. lol"
        working-directory: ./usr/bin
